### ISSUE TITLE
Support Rivine 1.0 API

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#371]
First investigate how much stuff has changed and how much time we need to implement this.
Let's discuss afterwards to check for a timing when we do this.

**Comment by lucasvanhalst** [comment]
This function (and some functions it calls) and the data objects will need to be changed:
https://github.com/our-city-app/mobicage-android-client/blob/1eb0df9113da600cc23db3d37fe5a54afed1b619/rogerthat/src/main/java/com/mobicage/rogerthat/util/security/ed25519/Ed25519.java#L181

Not sure about iOS but I think it will be less work since we use something generated from the golang rivine code

The wallet (embedded app) will need to be updated so it uses the new data structure.

**Comment by lucasvanhalst** [comment]
Pull requests:
- https://github.com/our-city-app/cordova-mobicage-payments-plugin/pull/1

**Comment by lucasvanhalst** [comment]
ready to review @bart-at-mobicage
