### ISSUE TITLE
Pool limit set on Mazraa

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#395]
Tokens can't be sent in the mobile wallet - see error in screenshot
Wallet address: 015f867544f490be10e9b6dd3c1fb20c35a942336a097256253b0b9d4eef7ef171e0b7370d3f3e

**Comment by sabrinasadik** [comment]
![2019-05-14 11 51 55](https://user-images.githubusercontent.com/31733464/57688867-bea44f80-763e-11e9-9e68-7bd6feea73ce.jpg)

**Comment by sabrinasadik** [comment]
<img width="426" alt="Screenshot 2019-05-14 at 11 56 24" src="https://user-images.githubusercontent.com/31733464/57689162-50ac5800-763f-11e9-9b7a-06cd410fa2af.png">

**Comment by LeeSmet** [comment]
The transaction pool has constraints for how big a single transaction can be (when binary encoded), the limits itself are currently set at 16kb for a single transaction (as defined here :https://github.com/threefoldtech/rivine/blob/master/types/constants.go#L129).

The exact lenght can be checked by binary encoding the transaction yourself (up to 100 inputs in a single transaction are a faily good limit though). If the tx is larger due to a large amount of inputs, it could be split up into multiple transactions under the hood (incurring a small increase in tx fee that needs to be payed, but that seems acceptable)

**Comment by bart-at-mobicage** [comment]
Discussed with Glen. For now we are just sorting on output amounts.

**Comment by lucasvanhalst** [comment]
looks like it worked
